package management

import (
	"context"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"os"
	"reflect"
	"slices"
	"strconv"
	"strings"
)

const fullSpecLabel = "io.loki.full.spec"

// The saved specification is public deployment metadata. Credentials enter
// through separately owned read-only files, never arguments or this record.
type fullContainerSpec struct {
	HostNetwork  bool              `json:"host_network,omitempty"`
	Name         string            `json:"name"`
	Service      string            `json:"service"`
	Image        string            `json:"image"`
	User         string            `json:"user"`
	Groups       []string          `json:"groups"`
	Command      []string          `json:"command"`
	Mounts       []FullMount       `json:"mounts"`
	Networks     []string          `json:"networks"`
	Capabilities []string          `json:"capabilities"`
	Publish      string            `json:"publish,omitempty"`
	Memory       int64             `json:"memory"`
	PIDs         int64             `json:"pids"`
	Seccomp      string            `json:"seccomp,omitempty"`
	Tmpfs        map[string]string `json:"tmpfs"`
}

func (s fullContainerSpec) digest() string {
	data, _ := json.Marshal(s)
	return fmt.Sprintf("%x", sha256.Sum256(data))
}

func (b *DockerFullBackend) containerName(r DeploymentReservation, service string) string {
	return b.Store.FullOwner() + "-" + strings.TrimPrefix(r.ID, "deployment-") + "-" + service
}

func (b *DockerFullBackend) labels(r DeploymentReservation, service string) []string {
	return []string{fullOwnerLabel + "=" + b.Store.FullOwner(), fullDeploymentLabel + "=" + r.ID, fullPlanLabel + "=" + r.PlanDigest, fullServiceLabel + "=" + service}
}

func (b *DockerFullBackend) containerIDs(ctx context.Context, r DeploymentReservation) ([]string, error) {
	data, err := b.command(ctx, "listing deployment containers", nil, "container", "ls", "--all", "--filter", "label="+fullOwnerLabel+"="+b.Store.FullOwner(), "--filter", "label="+fullDeploymentLabel+"="+r.ID, "--format", "{{.ID}}")
	if err != nil {
		return nil, err
	}
	ids, err := dockerLines(data)
	if err != nil {
		return nil, err
	}
	for _, id := range ids {
		if !dockerIDPattern.MatchString(id) {
			return nil, fmt.Errorf("invalid owned container ID")
		}
	}
	return ids, nil
}

type fullContainerInspection struct {
	ID, Name string
	Config   struct {
		Image, User     string
		Entrypoint, Cmd []string
		Labels          map[string]string
	}
	State struct {
		Running bool
		Status  string
	}
	HostConfig struct {
		Init                                   *bool
		PidMode, IpcMode, UTSMode              string
		Binds, VolumesFrom, Links              []string
		Devices, DeviceRequests                []json.RawMessage
		ReadonlyRootfs, Privileged             bool
		CapDrop, CapAdd, SecurityOpt, GroupAdd []string
		NetworkMode                            string
		Memory, PidsLimit                      int64
		PortBindings                           map[string][]struct{ HostIP, HostPort string }
		Tmpfs                                  map[string]string
	}
	Mounts []struct {
		Type, Name, Source, Destination string
		RW                              bool
	}
	NetworkSettings struct {
		Networks map[string]json.RawMessage
		Ports    map[string][]struct{ HostIP, HostPort string }
	}
}

func (b *DockerFullBackend) inspectContainer(ctx context.Context, id string) (fullContainerInspection, error) {
	var result fullContainerInspection
	data, err := b.command(ctx, "inspecting owned container", nil, "container", "inspect", "--format", "{{json .}}", id)
	if err != nil {
		return result, err
	}
	err = json.Unmarshal(data, &result)
	return result, err
}

func (b *DockerFullBackend) requireParent(r DeploymentReservation, c fullContainerInspection) error {
	if c.Config.Labels[fullOwnerLabel] != b.Store.FullOwner() || c.Config.Labels[fullDeploymentLabel] != r.ID {
		return fmt.Errorf("container belongs to another deployment; preserving it")
	}
	service := c.Config.Labels[fullServiceLabel]
	if service != "" {
		if service != "prepare" && !slices.Contains(r.Services, service) || c.Config.Labels[fullPlanLabel] != r.PlanDigest || strings.TrimPrefix(c.Name, "/") != b.containerName(r, service) {
			return fmt.Errorf("container has an incompatible deployment identity; preserving it")
		}
		return nil
	}
	// A job's parent namespace was generated by the protected launcher. Its
	// component and both immutable policy fingerprints must also be present.
	labels := c.Config.Labels
	if labels["io.loki.owner"] != "job" || labels["io.loki.job.id"] == "" || !deploymentDigestPattern.MatchString(labels["io.loki.policy.sha256"]) || !deploymentDigestPattern.MatchString(labels["io.loki.sandbox.sha256"]) {
		return fmt.Errorf("unrecognized deployment child container; preserving it")
	}
	component := labels["io.loki.resource.component"]
	if !slices.Contains([]string{"workload", "gateway", "publisher"}, component) {
		return fmt.Errorf("unknown deployment child component")
	}
	jobID := labels["io.loki.job.id"]
	if len(jobID) != 32 || !deploymentDigestPattern.MatchString(jobID+jobID) {
		return fmt.Errorf("invalid deployment child job identity; preserving it")
	}
	name := "loki-job-" + jobID
	if component != "workload" {
		name = "loki-job-" + component + "-" + jobID
	}
	if strings.TrimPrefix(c.Name, "/") != name {
		return fmt.Errorf("deployment child name differs from its job identity; preserving it")
	}
	return nil
}

func (b *DockerFullBackend) verifySpec(r DeploymentReservation, s fullContainerSpec, c fullContainerInspection) error {
	if err := b.requireParent(r, c); err != nil {
		return err
	}
	if c.Config.Labels[fullSpecLabel] != s.digest() || c.Config.Image != s.Image || c.Config.User != s.User || !reflect.DeepEqual(c.Config.Entrypoint, []string{s.Command[0]}) || !reflect.DeepEqual(c.Config.Cmd, s.Command[1:]) || !c.HostConfig.ReadonlyRootfs || c.HostConfig.Privileged || !slices.Contains(c.HostConfig.CapDrop, "ALL") || !slices.Contains(c.HostConfig.SecurityOpt, "no-new-privileges") && !slices.Contains(c.HostConfig.SecurityOpt, "no-new-privileges:true") || c.HostConfig.Memory != s.Memory || c.HostConfig.PidsLimit != s.PIDs {
		return fmt.Errorf("existing service differs from its saved execution policy; preserving it")
	}
	groups, expectedGroups := slices.Clone(c.HostConfig.GroupAdd), slices.Clone(s.Groups)
	slices.Sort(groups)
	slices.Sort(expectedGroups)
	capabilities, expectedCaps := slices.Clone(c.HostConfig.CapAdd), slices.Clone(s.Capabilities)
	for i := range capabilities {
		capabilities[i] = strings.TrimPrefix(capabilities[i], "CAP_")
	}
	slices.Sort(capabilities)
	slices.Sort(expectedCaps)
	if !slices.Equal(groups, expectedGroups) || !slices.Equal(capabilities, expectedCaps) {
		return fmt.Errorf("service gained unexpected group or kernel capability authority")
	}
	if !reflect.DeepEqual(c.HostConfig.Tmpfs, s.Tmpfs) {
		return fmt.Errorf("service temporary filesystem policy changed")
	}
	if c.HostConfig.Init == nil || !*c.HostConfig.Init || c.HostConfig.PidMode != "" || c.HostConfig.UTSMode != "" || c.HostConfig.IpcMode != "" && c.HostConfig.IpcMode != "private" || len(c.HostConfig.Devices) != 0 || len(c.HostConfig.DeviceRequests) != 0 || len(c.HostConfig.Binds) != 0 || len(c.HostConfig.VolumesFrom) != 0 || len(c.HostConfig.Links) != 0 {
		return fmt.Errorf("service gained undeclared process, device or legacy mount authority")
	}
	if err := verifyFullSecurityOptions(s, c.HostConfig.SecurityOpt); err != nil {
		return err
	}
	if s.Publish == "" && len(c.HostConfig.PortBindings) != 0 {
		return fmt.Errorf("service gained an unexpected published port")
	}
	if s.Publish != "" {
		bindings := c.HostConfig.PortBindings["18765/tcp"]
		if len(c.HostConfig.PortBindings) != 1 || len(bindings) != 1 || bindings[0].HostIP != "127.0.0.1" {
			return fmt.Errorf("MCP publication differs from its loopback policy")
		}
	}
	if len(c.Mounts) != len(s.Mounts) {
		return fmt.Errorf("service has unexpected filesystem mounts")
	}
	for _, expected := range s.Mounts {
		found := false
		for _, actual := range c.Mounts {
			source := actual.Source
			if actual.Type == "volume" {
				source = actual.Name
			}
			if actual.Type == expected.Kind && source == expected.Source && actual.Destination == expected.Target && actual.RW == !expected.ReadOnly {
				found = true
			}
		}
		if !found {
			return fmt.Errorf("service filesystem authority differs from its specification")
		}
	}
	actualNetworks := []string{}
	for name := range c.NetworkSettings.Networks {
		actualNetworks = append(actualNetworks, name)
	}
	if s.HostNetwork {
		if s.Service != "endpoints" || c.HostConfig.NetworkMode != "host" || len(s.Networks) != 0 || len(actualNetworks) != 1 || actualNetworks[0] != "host" {
			return fmt.Errorf("owned endpoint relay host network policy differs")
		}
	} else if len(s.Networks) == 0 {
		if c.HostConfig.NetworkMode != "none" {
			return fmt.Errorf("networkless service gained network authority")
		}
	} else {
		slices.Sort(actualNetworks)
		expected := slices.Clone(s.Networks)
		slices.Sort(expected)
		if !slices.Equal(actualNetworks, expected) {
			return fmt.Errorf("service network authority differs from its specification")
		}
	}
	return nil
}

func verifyFullSecurityOptions(spec fullContainerSpec, options []string) error {
	profile := ""
	for _, option := range options {
		if option == "no-new-privileges" || option == "no-new-privileges:true" {
			continue
		}
		value, ok := strings.CutPrefix(option, "seccomp=")
		if !ok || spec.Seccomp == "" || profile != "" || value == "unconfined" {
			return fmt.Errorf("service has an unexpected kernel security option")
		}
		profile = value
	}
	if spec.Seccomp == "" {
		return nil
	}
	if profile == "" {
		return fmt.Errorf("browser lost its declared sandbox seccomp profile")
	}
	if profile == spec.Seccomp {
		return nil
	}
	info, err := os.Lstat(spec.Seccomp)
	if err != nil || !info.Mode().IsRegular() || info.Size() > 1<<20 {
		return fmt.Errorf("trusted browser seccomp profile is unavailable")
	}
	data, err := os.ReadFile(spec.Seccomp)
	if err != nil {
		return err
	}
	var expected, actual any
	if json.Unmarshal(data, &expected) != nil || json.Unmarshal([]byte(profile), &actual) != nil || !reflect.DeepEqual(expected, actual) {
		return fmt.Errorf("browser seccomp policy differs from its trusted generation")
	}
	return nil
}

func (b *DockerFullBackend) createContainer(ctx context.Context, r DeploymentReservation, s fullContainerSpec) error {
	ids, err := b.containerIDs(ctx, r)
	if err != nil {
		return err
	}
	for _, id := range ids {
		current, err := b.inspectContainer(ctx, id)
		if err != nil {
			return err
		}
		if strings.TrimPrefix(current.Name, "/") == s.Name {
			if err := b.requireParent(r, current); err != nil {
				return err
			}
			if current.Config.Labels[fullSpecLabel] != s.digest() {
				return fmt.Errorf("existing service specification changed")
			}
			for network := range current.NetworkSettings.Networks {
				if !slices.Contains(s.Networks, network) && network != "none" && !(s.HostNetwork && network == "host") {
					return fmt.Errorf("service has an unexpected network; preserving it")
				}
			}
			for _, network := range s.Networks {
				if _, exists := current.NetworkSettings.Networks[network]; !exists {
					if _, err := b.command(ctx, "resuming owned network publication", nil, "network", "connect", "--alias", s.Service, network, s.Name); err != nil {
						return err
					}
				}
			}
			current, err = b.inspectContainer(ctx, id)
			if err != nil {
				return err
			}
			return b.verifySpec(r, s, current)
		}
	}
	args := []string{"container", "create", "--name", s.Name, "--init", "--restart", "unless-stopped", "--read-only", "--cap-drop", "ALL", "--security-opt", "no-new-privileges:true", "--user", s.User, "--memory", strconv.FormatInt(s.Memory, 10), "--pids-limit", strconv.FormatInt(s.PIDs, 10), "--shm-size", "256m"}
	for _, label := range append(b.labels(r, s.Service), fullSpecLabel+"="+s.digest()) {
		args = append(args, "--label", label)
	}
	for _, group := range s.Groups {
		args = append(args, "--group-add", group)
	}
	for _, capability := range s.Capabilities {
		args = append(args, "--cap-add", capability)
	}
	if s.Seccomp != "" {
		args = append(args, "--security-opt", "seccomp="+s.Seccomp)
	}
	if s.HostNetwork {
		if s.Service != "endpoints" || len(s.Networks) != 0 {
			return fmt.Errorf("host networking is scoped to the owned endpoint relay")
		}
		args = append(args, "--network", "host")
	} else if len(s.Networks) == 0 {
		args = append(args, "--network", "none")
	} else {
		args = append(args, "--network", s.Networks[0], "--network-alias", s.Service)
	}
	if s.Publish != "" {
		args = append(args, "--publish", s.Publish)
	}
	paths := []string{}
	for path := range s.Tmpfs {
		paths = append(paths, path)
	}
	slices.Sort(paths)
	for _, path := range paths {
		args = append(args, "--tmpfs", path+":"+s.Tmpfs[path])
	}
	for _, mount := range s.Mounts {
		value, err := dockerMountArgument(mount)
		if err != nil {
			return err
		}
		args = append(args, "--mount", value)
	}
	args = append(args, "--entrypoint", s.Command[0], s.Image)
	args = append(args, s.Command[1:]...)
	if _, err := b.command(ctx, "creating "+s.Service, nil, args...); err != nil {
		return err
	}
	for index, network := range s.Networks {
		if index == 0 {
			continue
		}
		if _, err := b.command(ctx, "connecting an owned private network", nil, "network", "connect", "--alias", s.Service, network, s.Name); err != nil {
			return err
		}
	}
	return nil
}
